[package]
name = "easy_esp"
version = "0.1.1"
edition = "2021"
description = "Wrapper around socket functionality to make using devices safer and easier"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.198"
serde_json = "1.0.116"
