[package]
name = "easy_esp"
version = "0.1.1"
edition = "2021"
description = "Wrapper around socket functionality to make using devices safer and easier"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queued_rust = "0.4.0"
serde = "1.0.198"
serde_derive = "1.0.198"
serde_json = "1.0.116"
tokio = "1.37.0"
zeromq = "0.3.5"
zmq = "0.10.0"

[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin.rs"